### ISSUE TITLE
Donkey Kong Visual Glitches & Crash

### ISSUE THREAD

**Issue by Senryoku** [Senryoku/SenBoy#1]
Donkey Kong (GB) suffer from major visual glitches (wrong BG?) and random crashes (execution of random instructions).

**Comment by shonumi** [comment]
Sounds like a similar problem I had with DKL2 a long time ago (random instructions, visual glitches...) -> http://code.google.com/p/gb-enhanced/issues/detail?id=1&can=1

Apparently, MBC1 will ignore the 2 high-bits if they'd technically end up reading from a bank that doesn't exist (that is to say, reading from a bank higher than the maximum banks a game uses). Just a guess, but that may be the issue here too.

Good luck ;)

**Comment by Senryoku** [comment]
Thanks a lot for your input! Unfortunately, after implementing your fix and checking my MBC1, I definitely think I have a bigger problem :( 
DKL2 works fine (after playing it for some minutes), but DK and DKL have the same kind of visual glitches (heaving flickering that looks like a wrong tile map or values for scroll x/y for one frame).
In the case of DKL, it seems to be tied to the use of HALT. My implementation is probably badly broken, but I can't pinpoint the exact problem. I also know that the timing is globally off, most games I tried didn't seem to care, but it may not be the case here.

Thanks again for your help anyway, that's really appreciated!

Edit: After some testing, I found out that Donkey Kong is modifying Scroll Y during its introduction, probably mid frame. The graphical glitches are thus probably caused by some timing issues.

**Comment by Senryoku** [comment]
Mostly corrected by d01dc31ad9df4e359cb3ce704e6e25717c16ecff and c633c7d720b7f33b7b75a2c79229ea14bc3bfec9
However, there is still some weird things going on:
- On startup, random tiles are displayed.
- At the end of every level, the bottom of the screen turns white (IIRC, the game sets LYC == 0x8F or something, maybe this is related? (I don't remember if it uses LYC interrupts or checks the bit in LCDSTAT))
